---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: geheim
  name: pvc-db-file
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
