apiVersion: v1
kind: Service
metadata:
  labels:
    app: geheim-app-service
  name: geheim-app-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: geheim-backend
